config/routes.rb
Rails.application.routes.draw do
  resources :bitcoins
  get 'bitcoin/index'
  get 'bitcoin/show'

  resources :posts
  root 'welcome#index'

end

app/models/bitcoin.rb
class Bitcoin < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bitcoin_controller.rb
class BitcoinController < ApplicationController
  def index
  end

  def show
  	require 'httparty'
  	require 'json'
  	puts ("[mjpark] bitcoin/show")

  	url_korbit = "https://api.korbit.co.kr/v1/ticker"
  	bitcoin_korbit = HTTParty.get(url_korbit)
  	puts (bitcoin_korbit)
  	korbit_data = JSON.parse(bitcoin_korbit)

  	url_coinone = "https://api.coinone.co.kr/ticker/"
  	bitcoin_coinone = HTTParty.get(url_coinone)
  	puts (bitcoin_coinone)
  	coinone_data = JSON.parse(bitcoin_coinone.body)

  	bitcoin_korbit_obj = Bitcoin.new
  	bitcoin_korbit_obj.company = "korbit"
  	bitcoin_korbit_obj.last = korbit_data["last"]
  	printf("%s : %s \n", bitcoin_korbit_obj.company, bitcoin_korbit_obj.last)
  	bitcoin_korbit_obj.save

  	# if Bitcoin.where(company: 'korbit').empty? 
  	# 	bitcoin_korbit_obj.save
  	# end
  	
  	bitcoin_coinone_obj = Bitcoin.new
  	bitcoin_coinone_obj.company = "coinone"
  	bitcoin_coinone_obj.last = coinone_data["last"]
  	printf("%s : %s\n", bitcoin_coinone_obj.company, bitcoin_coinone_obj.last)
  	bitcoin_coinone_obj.save

  	# if Bitcoin.where(company: 'coinone').empty?
  	# 	bitcoin_coinone_obj.save
  	# end

  	@bitcoins = Bitcoin.all
  	@korbit = korbit_data["last"]
  	@coinone = coinone_data["last"]

  end

end

app/controllers/bitcoins_controller.rb
class BitcoinsController < ApplicationController
  before_action :set_bitcoin, only: [:show, :edit, :update, :destroy]

  # GET /bitcoins
  # GET /bitcoins.json
  def index
    @bitcoins = Bitcoin.all
  end

  # GET /bitcoins/1
  # GET /bitcoins/1.json
  def show
  end

  # GET /bitcoins/new
  def new
    @bitcoin = Bitcoin.new
  end

  # GET /bitcoins/1/edit
  def edit
  end

  # POST /bitcoins
  # POST /bitcoins.json
  def create
    @bitcoin = Bitcoin.new(bitcoin_params)

    respond_to do |format|
      if @bitcoin.save
        format.html { redirect_to @bitcoin, notice: 'Bitcoin was successfully created.' }
        format.json { render :show, status: :created, location: @bitcoin }
      else
        format.html { render :new }
        format.json { render json: @bitcoin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bitcoins/1
  # PATCH/PUT /bitcoins/1.json
  def update
    respond_to do |format|
      if @bitcoin.update(bitcoin_params)
        format.html { redirect_to @bitcoin, notice: 'Bitcoin was successfully updated.' }
        format.json { render :show, status: :ok, location: @bitcoin }
      else
        format.html { render :edit }
        format.json { render json: @bitcoin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bitcoins/1
  # DELETE /bitcoins/1.json
  def destroy
    @bitcoin.destroy
    respond_to do |format|
      format.html { redirect_to bitcoins_url, notice: 'Bitcoin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bitcoin
      @bitcoin = Bitcoin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bitcoin_params
      params.require(:bitcoin).permit(:company, :last)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bitcoin_helper.rb
module BitcoinHelper
end

app/helpers/bitcoins_helper.rb
module BitcoinsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bitcoin/index.html.erb
<h1>Bitcoin#index</h1>
<p>Find me in app/views/bitcoin/index.html.erb</p>

app/views/bitcoin/show.html.erb
<h1>Bitcoin#show</h1>
<p></p>

<%= column_chart({"koribt" => @korbit, "coinone" => @coinone}, library: {width: 500}) %>

app/views/bitcoins/_form.html.erb
<%= simple_form_for(@bitcoin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :company %>
    <%= f.input :last %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bitcoins/edit.html.erb
<h1>Editing Bitcoin</h1>

<%= render 'form' %>

<%= link_to 'Show', @bitcoin %> |
<%= link_to 'Back', bitcoins_path %>

app/views/bitcoins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bitcoins</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Last</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bitcoins.each do |bitcoin| %>
      <tr>
        <td><%= bitcoin.company %></td>
        <td><%= bitcoin.last %></td>
        <td><%= link_to 'Show', bitcoin %></td>
        <td><%= link_to 'Edit', edit_bitcoin_path(bitcoin) %></td>
        <td><%= link_to 'Destroy', bitcoin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bitcoin', new_bitcoin_path %>

app/views/bitcoins/new.html.erb
<h1>New Bitcoin</h1>

<%= render 'form' %>

<%= link_to 'Back', bitcoins_path %>

app/views/bitcoins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @bitcoin.company %>
</p>

<p>
  <strong>Last:</strong>
  <%= @bitcoin.last %>
</p>

<%= link_to 'Edit', edit_bitcoin_path(@bitcoin) %> |
<%= link_to 'Back', bitcoins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bitcoin - Margin</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi" %>
  <%= javascript_include_tag "application", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Bitcoin</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <%= yield %>

    </div> <!-- /container -->
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>이 페이지는 "RCafe 프로젝트"의 Welcome 페이지입니다.</p>
<%= link_to "글작성", posts_path, class:'btn btn-default' %>
<%= line_chart 2 %>